#!/bin/bash
code --install-extension aaron-bond.better-comments
code --install-extension ahmadawais.shades-of-purple
code --install-extension ardenivanov.svelte-intellisense
code --install-extension bradlc.vscode-tailwindcss
code --install-extension chrmarti.regex
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dotjoshjohnson.xml
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension extensions.json
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.code-runner
code --install-extension foxundermoon.shell-format
code --install-extension fredjeck.fav
code --install-extension genieai.chatgpt-vscode
code --install-extension github.copilot
code --install-extension github.copilot-labs
code --install-extension grapecity.gc-excelviewer
code --install-extension hbenl.vscode-test-explorer
code --install-extension humao.rest-client
code --install-extension kamikillerto.vscode-colorize
code --install-extension kevinrose.vsc-python-indent
code --install-extension kisstkondoros.vscode-codemetrics
code --install-extension lextudio.restructuredtext
code --install-extension me-dutour-mathieu.vscode-github-actions
code --install-extension mechatroner.rainbow-csv
code --install-extension metaseed.metajump
code --install-extension mikeburgh.xml-format
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension njpwerner.autodocstring
code --install-extension oderwat.indent-rainbow
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-xml-0.25.0-darwin
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension selcuk-usta.code-complexity-report-generator
code --install-extension stkb.rewrap
code --install-extension svelte.svelte-vscode
code --install-extension vscodevim.vim
code --install-extension wallabyjs.quokka-vscode
code --install-extension withfig.fig
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.javascriptsnippets
code --install-extension yzhang.markdown-all-in-one
